wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.19.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1671194066
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      4: 3.7.11
      5: 0.12.16
      6: 4.19.0.dev0
      8:
      - 5
