wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1674560129.231785
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.9.16
      5: 0.13.9
      8:
      - 5
training.learning_rate:
  desc: null
  value: 0.009601556204105311
training.optimizer:
  desc: null
  value: sgd
