wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1674492532
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      4: 3.7.11
      5: 0.12.16
      8:
      - 5
data:
  desc: null
  value:
    augmentation.trigger: false
    batch_size: 4
    dataset: nyuv2
    input_size: null
    path: dataset
network:
  desc: null
  value:
    backbone: ResNet
    grad_method: null
    mtl_architecture: Split
    pretrained: false
    tasks: depth
    weighting: equal
reproduceability:
  desc: null
  value:
    o_seed: 29
    t_seed: true
training:
  desc: null
  value:
    early_stop: false
    epochs: 30
    learning_rate: 0.0001
    loss_function: cross_entropy
    o_checkpoint: null
    optimizer: sgd
    scheduler: multisteplr
    step: 10
    t_checkpoint: false
    weight_decay: 1.0e-05
wandb:
  desc: null
  value:
    entity: wandbdimar
    project_name: MTLwarehouse
    t_logger: true
