wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.19.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1671193793
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      4: 3.7.11
      5: 0.12.16
      6: 4.19.0.dev0
      8:
      - 5
batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: nyuv2
gpu:
  desc: null
  value: 0
grad_method:
  desc: null
  value: none
load_model:
  desc: null
  value: false
lr:
  desc: null
  value: 0.0001
mtl_architecture:
  desc: null
  value: Split
network:
  desc: null
  value: SegNet
project_name:
  desc: null
  value: MTLwarehouse
seed:
  desc: null
  value: 0
task:
  desc: null
  value: semantic
total_epochs:
  desc: null
  value: 100
wandb:
  desc: null
  value: true
weight:
  desc: null
  value: equal
