data: 
  path: dataset
  dataset: sim_warehouse #Options: nyuv2, sim_warehouse
  augmentation.trigger: False
  batch_size: 32
  input_size: null

network: 
  tasks: all #Options: all,semantic,depth,normals
  weighting: equal #Options: equal,dwa,uncert,autolambda,geometric
  backbone: DDRNet #Options: Resnet, SegNet, DDRNet
  mtl_architecture: Split #Options: Split, MTAN
  pretrained: False
  grad_method: null #Options: graddrop, pcgrad, cagrad

training: 
  epochs: 10
  optimizer_o: adam #Options: SGD, ADAM, ADAMW
  learning_rate: 0.0001
  weight_decay: 0.00001
  early_stop: False
  scheduler: multisteplr #options steplr, multisteplr
  step: 10
  loss_function: cross_entropy
  t_checkpoint: False
  o_checkpoint: null

reproduceability:
  t_seed: True
  o_seed: 29

wandb:
  t_logger: False
  project_name: MTLwarehouse
  entity: wandbdimar

sweep: 
  sweep_t: False
  sweep_o: 'configs/sweep_config.yaml'